# Generated by Django 6.0.7 on 2026-08-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Видано')),
                ('valid_date', models.IntegerField(default=30, verbose_name='Валідний n-днів:')),
            ],
        ),
    ]
