# Generated by Django 6.0.7 on 2026-08-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'промокод', 'verbose_name_plural': 'промокоди'},
        ),
        migrations.AddField(
            model_name='promocode',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, verbose_name='Максимум використань'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='times_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Використано разів'),
        ),
    ]
