# Generated by Django 6.0.7 on 2026-08-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0002_alter_promocode_options_promocode_max_uses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_date',
            field=models.IntegerField(default=30, verbose_name='Валідний (днів)'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='value',
            field=models.IntegerField(verbose_name='Знижка (%)'),
        ),
    ]
