# Generated by Django 6.0.7 on 2026-08-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpful_votes',
            field=models.PositiveIntegerField(default=0, verbose_name='корисно'),
        ),
        migrations.AddField(
            model_name='review',
            name='unhelpful_votes',
            field=models.PositiveIntegerField(default=0, verbose_name='некорисно'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='схвалено'),
        ),
    ]
