# Generated by Django 6.0.7 on 2026-08-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_mysterious',
            field=models.BooleanField(default=False, verbose_name='загадковий товар'),
        ),
        migrations.AddField(
            model_name='product',
            name='rarity',
            field=models.CharField(choices=[('common', 'Звичайний'), ('rare', 'Рідкісний'), ('epic', 'Епічний'), ('legend', 'Легендарний')], default='common', max_length=10, verbose_name='рідкісність'),
        ),
    ]
