# Generated by Django 6.0.7 on 2026-08-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rarity',
            field=models.CharField(choices=[('common', 'Звичайний'), ('rare', 'Рідкісний'), ('epic', 'Епічний'), ('legend', 'Легендарний'), ('mythic', 'Міфічний'), ('divine', 'Божественний')], default='common', max_length=20, verbose_name='рідкісність'),
        ),
    ]
