# Generated by Django 6.0.7 on 2026-08-12 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_alter_category_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='статус')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='загальна сума')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата оновлення')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='покупець')),
            ],
            options={
                'verbose_name': 'замовлення',
                'verbose_name_plural': 'замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='назва товару')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ціна')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='кількість')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='замовлення')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'позиція замовлення',
                'verbose_name_plural': 'позиції замовлення',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='імʼя')),
                ('last_name', models.CharField(max_length=50, verbose_name='прізвище')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='телефон')),
                ('city', models.CharField(max_length=100, verbose_name='місто')),
                ('address', models.TextField(verbose_name='адреса')),
                ('postal_code', models.CharField(max_length=20, verbose_name='поштовий індекс')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='orders.order', verbose_name='замовлення')),
            ],
            options={
                'verbose_name': 'адреса доставки',
                'verbose_name_plural': 'адреси доставки',
            },
        ),
    ]
