# Generated by Django 6.0.7 on 2026-08-23 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_coupon_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True, verbose_name='розрахункова дата доставки'),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20, verbose_name='попередній статус')),
                ('new_status', models.CharField(max_length=20, verbose_name='новий статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='дата зміни')),
                ('comment', models.TextField(blank=True, verbose_name='коментар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'зміна статусу',
                'verbose_name_plural': 'зміни статусів',
                'ordering': ['-changed_at'],
            },
        ),
    ]
